### PR TITLE
Update SonarQube URL

### PR DESCRIPTION
**Pull request by romeara**
Old is deprecated, SonarCloud is the future

### CODE REVIEW

**Comment by nickavv** [comment]
Uh oh, how did this add so many components?

**Comment by romeara** [comment]
An excellent question. Transitive dependencies and an updated thingy?

**Comment by nickavv** [comment]
Wouldn't it say updated then? I don't see any way that the actual bill of materials itself could have changed, outside of the Black Duck adding new components that it were missing before I guess?

But given that some of the "new" components are Apache Tomcat and Spring Framework I somehow doubt the KB was missing them

**Comment by romeara** [comment]
Or it re-mapped the identifiers (or added mappings for them) to the external ID lookup

**Pull request merged**
